name: flutter_iroiro
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  firebase_core: ^1.17.0
  firebase_analytics: ^9.1.8
  firebase_crashlytics: ^2.8.0
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  assets:
    - icons/
