// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp7B3hd_RdVwRGaD7k-b6w_ptBXVA2718',
    appId: '1:32508001290:web:237aad1183db1e9959b3f3',
    messagingSenderId: '32508001290',
    projectId: 'flutter-iroiro',
    authDomain: 'flutter-iroiro.firebaseapp.com',
    storageBucket: 'flutter-iroiro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSUgLgiZogy45PWIjgksaWrwbhVxrJGY',
    appId: '1:32508001290:android:4b9317a5a3a8bede59b3f3',
    messagingSenderId: '32508001290',
    projectId: 'flutter-iroiro',
    storageBucket: 'flutter-iroiro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL1A-Gzw7cRB2YmSWWblBlqiJpH1K2iMs',
    appId: '1:32508001290:ios:b89a80b21811635659b3f3',
    messagingSenderId: '32508001290',
    projectId: 'flutter-iroiro',
    storageBucket: 'flutter-iroiro.appspot.com',
    iosClientId:
        '32508001290-9fieuaqast316vn8bqt67mb3b18ebapb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIroiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL1A-Gzw7cRB2YmSWWblBlqiJpH1K2iMs',
    appId: '1:32508001290:ios:b89a80b21811635659b3f3',
    messagingSenderId: '32508001290',
    projectId: 'flutter-iroiro',
    storageBucket: 'flutter-iroiro.appspot.com',
    iosClientId:
        '32508001290-9fieuaqast316vn8bqt67mb3b18ebapb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIroiro',
  );
}
